version: "3.8"
services: 
  back-end:
    ports:
      - 8080:8080
    build: ./back
    environment:
      - REDIS_HOST=cache
  front-end:
    ports:
      - 5000:5000
    build: ./front
  cache: 
     image: redis:7.2.5
     
